### ISSUE TITLE
Having issues running "bash inference_demo.sh"

### ISSUE THREAD

**Issue by yipy0005** [bytedance/Protenix#1]
The following message occurred when I was running `bash inference_demo.sh` in the docker image:

```
Traceback (most recent call last):
  File "/workspace/runner/inference.py", line 30, in <module>
    from configs.configs_base import configs as configs_base
ModuleNotFoundError: No module named 'configs'
```

Appreciate if I could get some help to resolve this. It would be a shame to be unable to run such a good repository.

**Comment by zhangyuxuann** [comment]
Run `pip install -e .` before training and inference.
