### ISSUE TITLE
About reproducing PoseBusters performance

### ISSUE THREAD

**Issue by fuxuliu** [bytedance/Protenix#11]
Hi, Protenix team

Protenix is a impressive work of reproduction of AlphaFold 3

I noticed in your technical report that protenix got a great performance on the posebuesters benchmark.
Can you provide a script or tool that can reproduce this performance?

Looking forward to your reply, thanks

Best

**Comment by xinshi-chen** [comment]
Hi @fuxuliu,

Thank you for your interest! We plan to release our PoseBusters predictions very soon. Like AF3 and Chai-1, we'll provide the predictions in .sdf (ligand) and .pdb (environment) formats, which you can use with the PoseBusters Python package to reproduce the results.

In the meantime, you can input the sequences and SMILES of the PDBs into our inference script to obtain .mmcif files and confidence scores. As mentioned in Appendix B of our technical report, there's an evaluation workflow involving processing the .mmcif files to perform chain/atom permutations and extract the relevant .sdf and .pdb files. We plan to release these evaluation tools in a future update but there is no time estimation for this yet.
<img width="804" alt="image" src="https://github.com/user-attachments/assets/e9252595-4660-4526-9c2e-8ce78ec2fbf5">

**Comment by fuxuliu** [comment]
Hi @xinshi-chen 

Thanks for your reply.
I really look forward to your updating the evaluation tools as soon as possible.

**Comment by zhangyuxuann** [comment]
we released the top1-ranked postbusters structure in https://af3-dev.tos-cn-beijing.volces.com/pb_samples_release.tar.gz. Evaluation workflow will be released in the future.
