### ISSUE TITLE
Docker test command not working

### ISSUE THREAD

**Issue by jaketanderson** [bytedance/Protenix#16]
The command used to test that docker is working with CUDA is given in the Protenix README as `docker run --rm --gpus all nvidia/cuda:11.0-base nvidia-smi`. However, that seems to no longer be a valid command; instead, you need to use `docker run --rm --gpus all nvidia/cuda:11.0.3-base-${DIST} nvidia-smi` where `DIST` is your OS distribution. See: https://github.com/NVIDIA/nvidia-docker/issues/1735#issuecomment-1455744048

**Comment by zhangyuxuann** [comment]
Hi @jaketanderson , thanks, can you submit a PR to fix this?

**Comment by jaketanderson** [comment]
This was merged. Thank you! Closing.
