### ISSUE TITLE
RuntimeError: DataLoader worker (pid 572) is killed by signal: Bus error. It is possible that dataloader's workers are out of shared memory. Please try to raise your shared memory limit.

### ISSUE THREAD

**Issue by yipy0005** [bytedance/Protenix#2]
Hi, could I get an idea of how much memory is required?

Thank you!

**Comment by willx-y** [comment]
I think the simple work around could be using less dataloader workers with --num_workers x, the default value is 16.

**Comment by yipy0005** [comment]
Thanks for replying to my issue! I have one GPU (RTX 4090) and I just wanted to run inference. I tried `--data.num_dl_worker 1`, it didn't resolve the issue.

**Comment by zhangyuxuann** [comment]
> the default docker shared memory for interprocess communication is very low you can bypass it by mounting the host shared memory: add `-v /dev/shm:/dev/shm` to the docker run command

@yipy0005  can you try the method proposed by @nimrod-bio?  Thanks to @nimrod-bio, we will update the README later
```bash
docker run --gpus all -it -v $(pwd):/workspace -v /dev/shm:/dev/shm [ai4s-cn-beijing.cr.volces.com/infra/protenix:v0.0.1](http://ai4s-cn-beijing.cr.volces.com/infra/protenix:v0.0.1) /bin/bash
```

**Comment by v-shaoningli** [comment]
It is due to the limited shared memory in docker. 
You can check the memory by `df -lh | grep shm` or manually set  ```bash
    docker run --gpus all -it --shm-size=128g -v $(pwd):/workspace ai4s-cn-beijing.cr.volces.com/infra/protenix:v0.0.1 /bin/bash
    ```
