### ISSUE TITLE
Mismatched args in finetune_demo.h

### ISSUE THREAD

**Issue by Stamcini** [bytedance/Protenix#21]
Hi all,
In `finetune_demo.sh` line 38, args option `--load_checkpoint_ema_path ${checkpoint_path} \` mismatches with the option name given in  `/configs/configs_base.py` line 36, `"load_ema_checkpoint_path": "",`.

**Comment by zhangyuxuann** [comment]
Hi @Stamcini, thanks, i fixed this in [commit](https://github.com/bytedance/Protenix/commit/e5a8e71661adde95796226d74205594cc7df8f39)
