### ISSUE TITLE
Using AF3 weights with Protenix

### ISSUE THREAD

**Issue by abhinavb22** [bytedance/Protenix#23]
Is there a way to use the recently released AF3 weights using Protenix so that we can do a head-to-head comparison on specific use cases? OpenFold has a similar implementation to use AF2 weights with their PyTorch OpenFold model.

**Comment by zhangyuxuann** [comment]
Hi @abhinavb22, our model is released before the AF3 inference code is available, currently we do not support do a head-to-head comparison with released AF3. **Additionally, due to the limitations of the AF3-related license, this functionality will not be supported in the future.**
