### ISSUE TITLE
AssertionError: The provided precomputed MSA path of entities ['1'] does not exists:  None

### ISSUE THREAD

**Issue by SuperTiefeng** [bytedance/Protenix#3]
Hi. When I use this code to predict a protein structure, since I don't have MSA, I set the precomputed MSA path to None, but it reports an error:

**2024-11-10 19:46:52,360 [/root/protenix/runner/inference.py:170] INFO __main__: The provided precomputed MSA path of entities ['1'] does not exists: 
None:
Traceback (most recent call last):
  File "/root/protenix/protenix/data/infer_data_pipeline.py", line 212, in __getitem__
    data, atom_array, _ = self.process_one(
  File "/root/protenix/protenix/data/infer_data_pipeline.py", line 115, in process_one
    InferenceMSAFeaturizer.make_msa_feature(
  File "/root/protenix/protenix/data/msa_featurizer.py", line 1145, in make_msa_feature
    msa_feats = InferenceMSAFeaturizer.get_inference_prot_msa_features_for_assembly(
  File "/root/protenix/protenix/data/msa_featurizer.py", line 1051, in get_inference_prot_msa_features_for_assembly
    assert opexists(
AssertionError: The provided precomputed MSA path of entities ['1'] does not exists: 
None**

Below is my input json:

```
[{
    "sequences": [
        {
            "proteinChain": {
                "sequence": "MGSSHHHHHHSSGLVPRGSHMSGKIQHKAVVPAPSRIPLTLSEIEDLRRKGFNQTEIAELYGVTRQAVSWHKKTYGGRLTTRQIVQQNWPWDTRKPHDKSKAFQRLRDHGEYMRVGSFRTMSEDKKKRLLSWWKMLRDNDLVLEFDPSIEPYEGMAGGGFRYVPRDISDDDLLIRVNEHTQLTAEGELLWSWPDDIEELLSEP",
                "count": 1,
                "msa": {
                    "precomputed_msa_dir": "None",
                    "pairing_db": "uniprot"
                }

            }
        }
    ],
    "modelSeeds": [],
    "assembly_id": "1",
    "name": "7r6r"
}
]
```

Did I miss or misunderstand something?

**Comment by zhangyuxuann** [comment]
Hi @SuperTiefeng , if you do not have a msa, you can set **--use_msa false** to skip it in the inference_demo.sh
```bash
export LAYERNORM_TYPE=fast_layernorm

N_sample=5
N_step=200
N_cycle=10
seed=101
use_deepspeed_evo_attention=true
input_json_path="./examples/example.json"
# wget -P /af3-dev/release_model/ https://af3-dev.tos-cn-beijing.volces.com/release_model/model_v1.pt
load_checkpoint_path="/af3-dev/release_model/model_v1.pt"
dump_dir="./output"

python3 runner/inference.py \
--seeds ${seed} \
--load_checkpoint_path ${load_checkpoint_path} \
--dump_dir ${dump_dir} \
--input_json_path ${input_json_path} \
--use_deepspeed_evo_attention ${use_deepspeed_evo_attention} \
--model.N_cycle ${N_cycle} \
--sample_diffusion.N_sample ${N_sample} \
--sample_diffusion.N_step ${N_step} \
--use_msa false
```
By the way, thanks for your feedback, we will add this description in the README later.

**Comment by SuperTiefeng** [comment]
Hi




It works. Thank you very much!




Cheers,

Tiefeng Song







-----原始邮件-----
发件人:"Yuxuan Zhang" ***@***.***>
发送时间:2024-11-11 11:26:41 (星期一)
收件人: bytedance/Protenix ***@***.***>
抄送: SuperTiefeng ***@***.***>, Mention ***@***.***>
主题: Re: [bytedance/Protenix] AssertionError: The provided precomputed MSA path of entities ['1'] does not exists: None (Issue #3)






Hi @SuperTiefeng , if you do not have a msa, you can set --use_msa false to skip it in the inference_demo.sh

export LAYERNORM_TYPE=fast_layernorm

N_sample=5
N_step=200
N_cycle=10
seed=101
use_deepspeed_evo_attention=true
input_json_path="./examples/example.json"# wget -P /af3-dev/release_model/ https://af3-dev.tos-cn-beijing.volces.com/release_model/model_v1.pt
load_checkpoint_path="/af3-dev/release_model/model_v1.pt"
dump_dir="./output"

python3 runner/inference.py \
--seeds ${seed} \
--load_checkpoint_path ${load_checkpoint_path} \
--dump_dir ${dump_dir} \
--input_json_path ${input_json_path} \
--use_deepspeed_evo_attention ${use_deepspeed_evo_attention} \
--model.N_cycle ${N_cycle} \
--sample_diffusion.N_sample ${N_sample} \
--sample_diffusion.N_step ${N_step} \
--use_msa false

By the way, thanks for your feedback, we will add this description in the README later.

**Comment by Kqiii** [comment]
Closing this issue as the problem has been resolved. Please feel free to reopen it if you have any further questions.
