### ISSUE TITLE
How to run "protenix predict -- input examples/example.json"?

### ISSUE THREAD

**Issue by Rayca0** [bytedance/Protenix#41]
Hi. I have successfully installed protenix by using pip in my conda env. When I tried to run the command "protenix predict --input examples/example.json --out_dir  ./output --seeds 101", it reports an runtime error, saying it cannot read a special ligand file: examples/example.json. 
I went to search for the folder. It seems like the entire folder, "examples", is not installed along with the pip installation. Is this a normal thing? should i download the folder manually and put it somewhere?

**Comment by zhangyuxuann** [comment]
Hi @Rayca0  After you have install the protenix by pip. The examples folder is in this repo. You can 
```
git clone https://github.com/bytedance/Protenix yourfolder
cd yourfolder
# then run protenix predict --xxx
```
