### ISSUE TITLE
About Protenix: Protein + X

### ISSUE THREAD

**Issue by jiaweiguan** [bytedance/Protenix#6]
Great work! 
Regarding the name Protenix: Protein + X, what is the meaning of the letters i and n swapped, just out of curiosity

**Comment by zhangyuxuann** [comment]
@jiaweiguan emm, it's a good question.

**Comment by xinshi-chen** [comment]
Some unofficial explanations:

- The "ix" ending gives it a smoother, more fluid pronunciation.
- "nix" is often associated with tech and innovation, adding a sense of cutting-edge sophistication.
- The swap of "i" and "n" subtly evokes transformation—taking the familiar "protein" and making it feel fresh and exciting.

Ultimately, we just prefer it this way!

**Comment by jiaweiguan** [comment]
@zhangyuxuann @xinshi-chen Hi! 
Regarding align, there seems to be a misunderstanding. `x` is a GT structure, but the variable uses `pred_pose`.
In addition, regarding the stop gradient during training, using `GT` to align `pred`, and stop the gradient of `GT` will be very different from using `pred` to align `GT`, and stop the gradient of `pred`. In fact, the alignment process should not produce gradients. But in the pseudo code of af3, `pred` is used to align `GT`. Do you think this is problematic?

https://github.com/bytedance/Protenix/blob/eb56f7e682c3668647ce29421b479323d452533b/protenix/metrics/rmsd.py#L243-L252

**Comment by zhangyuxuann** [comment]
@jiaweiguan I think in af3, it use `GT` to align on `pred`. However, we think it has a typo in the algorithm box.
![image](https://github.com/user-attachments/assets/bcacf0d0-7404-4f3e-ae42-026cc9d1f25f)
As shown in the technical report
![image](https://github.com/user-attachments/assets/c01eeeb1-5c59-4a03-af95-4905f37c429c)
