### ISSUE TITLE
How is masking implemented for padded structures?

### ISSUE THREAD

**Issue by ardagoreci** [bytedance/Protenix#9]
Hi,

Amazing work on the reproduction!

I was wondering how masking is implemented in attention. In the standard_multihead_attention method for instance, there is no mask to account for residues that might be padded during training. Having to mask things all the time was annoying in my repo and I am really curious how you got around this issue.

def standard_multihead_attention(
        self,
        a: torch.Tensor,
        s: torch.Tensor,
        z: torch.Tensor,
        inplace_safe: bool = False,
    ) -> torch.Tensor:
        """Used by Algorithm 7/20

        Args:
            a (torch.Tensor): the single feature aggregate per-atom representation
                [..., N_token, c_a]
            s (torch.Tensor): single embedding
                [..., N_token, c_s]
            z (torch.Tensor): pair embedding, used for computing pair bias.
                [..., N_token, N_token, c_z]
            inplace_safe (bool): Whether it is safe to use inplace operations. Defaults to False.

        Returns:
            torch.Tensor: the updated a from AttentionPairBias
                [..., N_token, c_a]
        """

Arda

**Comment by v-shaoningli** [comment]
In AF3, the batch size is `1` (per GPU) so we do not use mask. As for its sampling, it generates **same** 48 protein so we do not need mask as well.

**Comment by zhangyuxuann** [comment]
Hi @ardagoreci, due to GPU memory limitations, the batch size during different training stages (AF2, AF3) is set to 1, allowing for simplification of some batch-level masks. However, using masks remains a more elegant approach, and we may consider incorporating this in future versions.
